name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run tests
      run: poetry run pytest
    - name: Check Coverage
      run: | 
        poetry run coverage run -m pytest
        poetry run coverage xml
    - name: Python Coverage
      uses: orgoro/coverage@v3.1
      with:
        # local path to a coverage xml file like the output of pytest --cov
        coverageFile: "coverage.xml" 
        # github token
        token: ${{ secrets.GITHUB_TOKEN }}
        # the coverage threshold for average over all files [0,1]
        thresholdAll: 0.7
            
