name: Run Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Tests and Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run tests
      run: poetry run pytest
    - name: Check Coverage
      run: | 
        poetry run coverage run -m pytest
        poetry run coverage xml
    - name: Python Coverage
      uses: orgoro/coverage@v3.1
      with:
        # local path to a coverage xml file like the output of pytest --cov
        coverageFile: "coverage.xml" 
        # github token
        token: ${{ secrets.GITHUB_TOKEN }}
        # the coverage threshold for average over all files [0,1]
        thresholdAll: 0.7
    - name: Dynamic Badges
      uses: Schneegans/dynamic-badges-action@v1.7.0
      with:
        # Your secret with the gist scope
        auth: ${{ secrets.GIST_SECRET }}
        # The ID of the gist to use
        gistID: 0a4e8c66088021da4280d4999bfc1acf
        # The *.json or *.svg filename of the badge data
        filename: grouped-data-to-2d-histogram-coverage.json
        # The left text of the badge
        label: Coverage
        # The right text of the badge
        message: 80 %
        valColorRange: 80
        maxColorRange: 100
        minColorRange: 0
        forceUpdate: true
                      
